[build]
  publish = "mattvinc-radio-app"
  command = "npm run build && mv build mattvinc-radio-app"

[[redirects]]
  from = "/mattvinc-radio-app/*"
  to = "/mattvinc-radio-app/index.html"
  status = 200
